### ISSUE TITLE
Ability to change baseUrl

### ISSUE THREAD

**Issue by faradoxuzb** [Dhi13man/open_route_service#17]
Thank you for great library. 
We have installed openrouteservice in our server, so this means our api endpoint is not https://api.openrouteservice.org.
Can we change the baseUrl to our own subdomain?

**Comment by Dhi13man** [comment]
Hey. I have raise a PR keeping your requirement in mind, and with other changes: #18 

Would love it if you could give it a review. Will get it deployed once done.

**Comment by Dhi13man** [comment]
Released v1.2.4 with this flexibility added.
