### ISSUE TITLE
Add project setup to README.md

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [Dhi13man/open_route_service#6]
Apart from the usage instruction, there is currently nothing on how to setup the project and run the files in development mode.

This would be helpful for contributions.

**Comment by Dhi13man** [comment]
Ah, will do that.

**Comment by Dhi13man** [comment]
Made some changes to README.MD in the [latest commit](https://github.com/Dhi13man/open_route_service/commit/5b53a5034bd22c93ae7aed3fc0c9d5ee403b2b1f).

I hope that's more than enough for contributors. If not, feel free to include what you'd like to see.

Closing the issue as of now. :)
